function gameLoadMedusa(game,scene,C) {
    scene.sprites.medusa={
        tags:["enemy","hitable","tostart","killplayer","toclear","stagesprite","bright"],
        hitboxX:2, hitboxY:2,
        hitboxWidth:12, hitboxHeight:12,
        zIndex:C.ENEMYZINDEX,
        animations:[
            {
                flying:{
                    loop:true,
                    cells:game.cells.medusaFlying,
                    speed:0.1
                },
                still:{
                    cells:game.cells.medusaStill
                },
                bubble:{
                    loop:true,
                    cells:game.cells.medusaBubble,
                    speed:0.1
                },
                stunned:{
                    cells:game.cells.medusaStunned
                },
                panic:{
                    loop:true,
                    cells:game.cells.medusaPanic,
                    speed:0.2
                },
                washed:{
                    cells:game.cells.medusaWashed
                }
            },{
                flying:{
                    loop:true,
                    cells:game.cells.angryMedusaFlying,
                    speed:0.1
                },
                still:{
                    cells:game.cells.angryMedusaStill
                },
                bubble:{
                    loop:true,
                    cells:game.cells.angryMedusaBubble,
                    speed:0.1
                },
                stunned:{
                    cells:game.cells.angryMedusaStunned
                },
                panic:{
                    loop:true,
                    cells:game.cells.angryMedusaPanic,
                    speed:0.2
                },
                washed:{
                    cells:game.cells.angryMedusaWashed
                }
            }
        ],
        properties:{
            brightnessX:8,
            brightnessY:8,
            brightness:16,
            onBubbleRelease:{
                addNewSprite:"medusa",
                setMode:1
            },
            onBubblePopped:{
                scatterAround:true
            },
            onDie:{
                spawnBonus:"tier1points",
                spawnBonusSequence:C.SPAWNBONUSSEQUENCE
            }
        },
        states:{
            default:{
                collisions:C.BOUNCINGENEMYCOLLISIONS,
                onBubbled:C.cageInBubble,
                onSnowed:C.cageInSnow,
                onSquished:C.squished,
                onWashed:C.washed,
                onRushed:C.rushed,
                onBulleted:C.bulleted,
                onFrozen:C.frozen,
                onUnfrozen:C.unfrozen,
                onSucked:C.sucked,
                onGunned:C.gunned,
                onEnter:(game,scene,sprite)=>{
                    C.enemyStart(game,scene,sprite);
                    C.floatingEnemyStart(game,scene,sprite);
                    if (!sprite.speedX) sprite.setSpeedX(C.RND.randomBool(0.5)?-C.MEDUSAMOVESPEEDX[sprite.mode]:C.MEDUSAMOVESPEEDX[sprite.mode]);
                    if (!sprite.speedY) sprite.setSpeedY(C.RND.randomBool(0.5)?-C.MEDUSAMOVESPEEDY[sprite.mode]:C.MEDUSAMOVESPEEDY[sprite.mode]);
                },
                onLogic:(game,scene,sprite)=>{
                    C.commonEnemyLogic(game,scene,sprite);
                    C.enemyFlying(game,scene,sprite,C.MEDUSAMOVESPEEDX,C.MEDUSAMOVESPEEDY);
                }
                    
            },
            preparing:C.ENEMYPREPARING,
            kill:C.ENEMYKILL,
            snowing:C.ENEMYSNOWING,
            stunned:C.ENEMYSTUNNED,
            rolling:C.ENEMYROLLING,
            sucking:C.ENEMYSUCKING,
            sucked:C.ENEMYSUCKED
        },
    }
}