function gameLoadSnake(game,scene,C) {
    scene.sprites.snake={
        tags:["enemy","hitable","tostart","killplayer","toclear","stagesprite","bright"],
        hitboxX:2, hitboxY:2,
        hitboxWidth:12, hitboxHeight:14,
        zIndex:C.ENEMYZINDEX,
        minSpeedX:C.MINSPEEDX, maxSpeedX:C.MAXSPEEDX, minSpeedY:C.MINSPEEDY, maxSpeedY:C.MAXSPEEDY,
        animations:[
            {
                still:{
                    cells:game.cells.snakeStill,
                },
                wait:{
                    loop:true,
                    cells:game.cells.snakeWaiting,
                    speed:0.1
                },
                jump:{
                    loop:true,
                    cells:game.cells.snakeJumping,
                    speed:0.1
                },
                dead:{
                    cells:game.cells.snakeStill,
                },
                bubble:{
                    loop:true,
                    cells:game.cells.snakeBubble,
                    speed:0.1
                },
                stunned:{
                    cells:game.cells.snakeStunned
                },
                panic:{
                    loop:true,
                    cells:game.cells.snakePanic,
                    speed:0.2
                },
                washed:{
                    cells:game.cells.snakeWashed
                }
            },{
                still:{
                    cells:game.cells.angrySnakeStill,
                },
                wait:{
                    loop:true,
                    cells:game.cells.angrySnakeWaiting,
                    speed:0.1
                },
                jump:{
                    loop:true,
                    cells:game.cells.angrySnakeJumping,
                    speed:0.1
                },
                dead:{
                    cells:game.cells.angrySnakeStill,
                },
                bubble:{
                    loop:true,
                    cells:game.cells.angrySnakeBubble,
                    speed:0.1
                },
                stunned:{
                    cells:game.cells.angrySnakeStunned
                },
                panic:{
                    loop:true,
                    cells:game.cells.angrySnakePanic,
                    speed:0.2
                },
                washed:{
                    cells:game.cells.angrySnakeWashed
                }
            }
        ],
        properties:{
            brightnessX:8,
            brightnessY:8,
            brightness:16,
            onBubbleRelease:{
                addNewSprite:"snake",
                setMode:1
            },
            onBubblePopped:{
                scatterAround:true
            },
            onDie:{
                spawnBonus:"tier1points",
                spawnBonusSequence:C.SPAWNBONUSSEQUENCE
            }
        },
        states:{
            default:{
                collisions:C.ENEMYCOLLISIONS,
                onBubbled:C.cageInBubble,
                onSnowed:C.cageInSnow,
                onSquished:C.squished,
                onWashed:C.washed,
                onRushed:C.rushed,
                onBulleted:C.bulleted,
                onFrozen:C.frozen,
                onUnfrozen:C.unfrozen,
                onSucked:C.sucked,
                onGunned:C.gunned,
                onEnter:(game,scene,sprite)=>{
                    C.enemyStart(game,scene,sprite);
                    C.walkingEnemyStart(game,scene,sprite);
                    sprite.timer=C.SNAKEJUMPTIMER;
                },
                onLogic:(game,scene,sprite)=>{
                    C.commonEnemyLogic(game,scene,sprite);
                    C.applyVerticalWarp(sprite);
                    if (sprite.collisions.bottom && (sprite.collisions.bottom.wall||sprite.collisions.bottom.solidwall)) {
                        sprite.setSpeedX(0);
                        sprite.changeAnimation(sprite.animations[sprite.mode].wait);
                        if (sprite.timer)
                            sprite.timer--;
                        else {
                            sprite.timer=C.SNAKEJUMPTIMER;
                            sprite.setSpeedX(C.SNAKEMOVESPEED[sprite.mode]*(sprite.flipX?-1:1));
                            sprite.setSpeedY(C.SNAKEJUMPSPEED);
                        }
                    } else {
                        C.enemyChangeDirectionOnWall(game,scene,sprite);
                        sprite.changeAnimation(sprite.animations[sprite.mode].jump);
                    }
                }
            },
            preparing:C.ENEMYPREPARING,
            kill:C.ENEMYKILL,
            snowing:C.ENEMYSNOWING,
            stunned:C.ENEMYSTUNNED,
            rolling:C.ENEMYROLLING,
            sucking:C.ENEMYSUCKING,
            sucked:C.ENEMYSUCKED
        },
    }
}